:construction_worker: travis update

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,14 +14,19 @@ script:
     (
       tag=$(git rev-parse --short HEAD)
       docker build . -t gin-example:${tag} -f ./docker/Dockerfile
-
+      docker images
       docker run -d -p 80:8080 gin-example:${tag}
-      curl --fail http://127.0.0.1/ping
-        
-      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
-      docker tag gin-example:${tag} jolla20i8/gin-example:${tag}
-      docker tag jolla20i8/gin-example:${tag} jolla20i8/gin-example:latest
-      docker push jolla20i8/gin-example:${tag}
-      docker push jolla20i8/gin-example:latest
+      
+      if $(curl --fail http://127.0.0.1/ping) ;then
+      do 
+        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+        docker tag gin-example:${tag} jolla20i8/gin-example:${tag}
+        docker tag jolla20i8/gin-example:${tag} jolla20i8/gin-example:latest
+        docker push jolla20i8/gin-example:${tag}
+        docker push jolla20i8/gin-example:latest
+      else
+        echo "test fail, please check"
+        exit 1
+      fi
 
     )
